# Generated by Django 4.2.16 on 2024-12-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_communities_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='avatar',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='communities',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='communities',
            name='free',
            field=models.BooleanField(verbose_name='Свободный вход'),
        ),
        migrations.AlterField(
            model_name='communities',
            name='name',
            field=models.CharField(max_length=75, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='communities',
            name='slug',
            field=models.SlugField(verbose_name='Служебный код'),
        ),
    ]
