# Generated by Django 4.2.16 on 2024-12-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_alter_communities_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='avatar',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
