# Generated by Django 4.2.16 on 2024-12-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_alter_communities_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='avatar',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='', verbose_name='Аватар'),
        ),
    ]
